#!/usr/bin/env python3
"""
Verify the new SVG is correct by:
1. Detecting on charuco_reference.png (generated by OpenCV, should be perfect)
2. Comparing first marker's bit grid from new SVG vs OpenCV bytesList
"""
import sys
import cv2
import numpy as np


def check_svg_bits():
    """Parse new SVG and compare marker 0 data bits with OpenCV dict."""
    import re
    from pathlib import Path
    from collections import defaultdict

    svg_path = '1_biometriscan/calibration/charuco_A4_30mm.svg'
    text = Path(svg_path).read_text(encoding='utf-8')

    rects = re.findall(
        r'<rect\s+x="([\d.]+)"\s+y="([\d.]+)"\s+width="([\d.]+)"\s+height="([\d.]+)"\s+fill="black"',
        text,
    )
    bits = [(float(x), float(y), float(w)) for x, y, w, h in rects if float(w) < 10]

    # Group into squares (30mm grid)
    sq_mm = 30.0
    squares = defaultdict(list)
    for bx, by, bsize in bits:
        col = int(bx / sq_mm)
        row = int(by / sq_mm)
        squares[(col, row)].append((bx - col * sq_mm, by - row * sq_mm))

    dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_250)

    # Check first 4 marker squares (in row-major order)
    # OpenCV marker IDs: row0→cols 1,3,5 → IDs 0,1,2; row1→cols 0,2,4,6 → IDs 3,4,5,6
    marker_sq_order = [(1, 0), (3, 0), (5, 0), (0, 1)]  # col,row → marker IDs 0,1,2,3

    for mid, (col, row) in enumerate(marker_sq_order):
        local_bits = squares.get((col, row), [])
        if not local_bits:
            print(f"Marker {mid} at ({col},{row}): NOT FOUND in SVG")
            continue

        xs = sorted(set(round(x, 2) for x, y in local_bits))
        ys = sorted(set(round(y, 2) for x, y in local_bits))
        n = len(xs)
        if n != 6:
            print(f"Marker {mid}: expected 6 cols, got {n}")
            continue

        grid = np.zeros((6, 6), dtype=np.uint8)
        xi = {x: i for i, x in enumerate(xs)}
        yi = {y: i for i, y in enumerate(ys)}
        for x, y in local_bits:
            grid[yi[round(y, 2)], xi[round(x, 2)]] = 1

        # Extract inner 4×4 data bits
        data = grid[1:5, 1:5]

        # OpenCV dict bits (MSB first, row by row)
        ref_bits = np.unpackbits(dictionary.bytesList[mid].flatten())[:16].reshape(4, 4)

        # In the SVG, black rect = pixel 0 in generateImageMarker = dict bit 0.
        # verify grid stores 1 where black rect exists, so grid == (1 - ref_bits).
        match = np.array_equal(data, 1 - ref_bits)
        print(f"Marker {mid} at ({col},{row}): SVG data bits {'MATCH' if match else 'MISMATCH'} OpenCV dict")
        if not match:
            print(f"  SVG  : {data}")
            print(f"  OpenCV (inverted): {1 - ref_bits}")


def check_reference_image():
    """Run CharucoDetector on the reference PNG (should detect all 31 markers)."""
    img = cv2.imread('/repo/photos/charuco_reference.png')
    if img is None:
        print("charuco_reference.png not found")
        return

    dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_250)
    board = cv2.aruco.CharucoBoard((7, 9), 0.030, 0.021, dictionary)
    detector = cv2.aruco.CharucoDetector(board)

    charuco_corners, charuco_ids, marker_corners, marker_ids = detector.detectBoard(img)
    n_markers = len(marker_ids) if marker_ids is not None else 0
    n_charuco = len(charuco_ids) if charuco_ids is not None else 0

    print(f"\nReference image ({img.shape[1]}×{img.shape[0]}):")
    print(f"  ArUco markers detected: {n_markers}/31")
    print(f"  ChArUco corners: {n_charuco}")
    if marker_ids is not None:
        print(f"  Marker IDs: {sorted(marker_ids.flatten().tolist())}")


if __name__ == '__main__':
    check_svg_bits()
    check_reference_image()
